using FileIndex.Models;

namespace FileIndex
{
    public interface IFileLoader
    {
        /// <summary>
        /// Will load all files metadata recursivly from a given directory
        /// </summary>
        /// <param name="path">Path of the directory from which files would be loaded recursively</param>
        /// <returns>return dictionary where key is fileID(autogenerated GUID) and value is FileInfo object</returns>
        FileInfoContainer LoadFileInfos(string path);
    }
}
